server:
  port: 8881

#thymeleaf start
spring:
  thymeleaf:
    cache: false # 开发时关闭缓存
    content-type: text/html # Content-Type value.
    enabled: true # 是否启用
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1/database1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#thymeleaf end



# mybatis start
mybatis:
  type-aliases-package: com.rudy.miaosha.domain   # 别名包
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100  # 每次去数据库拿取的条数
    default-statement-timeout: 3000
  mapper-locations: classpath:com/rudy/miaosha/mapper/*.xml
# mybatis end

#jdbc
#jdbc end


#redis
redis:
  host: 192.168.200.127
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
#redis end
